name: jjudsonlohman
favicon: null
layout_spectrum: 0.14001388126052916
typography_spectrum: 0.4307934921234846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.11249812645837665
  lightness: 0.27342612762004137
  saturation: 0.833959586918354
  rhythmicContrast: 0.26326858438551426
purpose: []
